---
title:               Blogging in Berlin
tagline:             A bit of everything from Berlin.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Joost Oostdijk
twitter:             joustava
linkedin:            fi.linkedin.com/in/joostoostdijk
github:              joustava
bitbucket_url:       http://bitbucket.oostdijk.net/
email:               joustava@gmail.com
google_analytics_id: UA-37405240-1
disqus_shortname:    blogginginberlin
